
  # Name your project! Project names should contain only lowercase characters
  # and underscores. A good package name should reflect your organization's
  # name or the intended use of these models
  name: 'dbt_project'
  version: '1.0.0'

  # This setting configures which "profile" dbt uses for this project.
  profile: 'dbt_project'

  # These configurations specify where dbt should look for different types of files.
  # The `model-paths` config, for example, states that models in this project can be
  # found in the "models/" directory. You probably won't need to change these!
  model-paths: ["dw_sqlite/models", "dw_duckdb/models"]
  analysis-paths: ["dw_sqlite/analyses", "dw_duckdb/analyses"]
  test-paths: ["dw_sqlite/tests", "dw_duckdb/tests"]
  seed-paths: ["dw_sqlite/seeds", "dw_duckdb/seeds"]
  macro-paths: ["dbt_macros"]
  snapshot-paths: ["dw_sqlite/snapshots", "dw_duckdb/snapshots"]

  clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
    - "logs"


  # Configuring models
  # Full documentation: https://docs.getdbt.com/docs/configuring-models

  # In this example config, we tell dbt to build all models in the example/
  # directory as views. These settings can be overridden in the individual model
  # files using the `{{ config(...) }}` macro.

  models:
    dbt_project:
      dw_sqlite:
        +enabled: "{{ target.type == 'sqlite_dev' }}"

      dw_duckdb:
        +enabled: "{{ target.type == 'duckdb_dev' }}"
