"""
inspector.py

Creates an agent to analyze the JSON files generated by the profiler.
"""
from claude.agents.data_discovery_agent__final.tools import tools 
from claude.agents.data_discovery_agent__final.tools.utils import executor, assistant

from pathlib import Path


# Assigning the SKILL as the system prompt
def load_skill(skill_name) -> str:
    skill_path = Path(__file__).parent / f"{skill_name}.md"
    return skill_path.read_text(encoding="utf-8")


def inspect_structure_from_profile(profile_json: dict):
    """
        Receives the profiling JSON from the previous steps and spins up agents to
         analyze its structure.
    """
    messages = []

    system_prompt = load_skill(skill_name="STRUCTURE")

    for datasource, profile in profile_json.items():
        inspector_messages = [
                 {
                     "role": "user",
                     "content": f"""
                         Analyze the data of {datasource}, with the provided JSON: 
                             {profile}
                         """
                 },
                 {
                     "role": "assistant",
                     "content": f"""I'll analyze the {datasource} table data and provide you with a comprehensive discovery report covering Primary Keys, Foreign Keys, Orchestration, and Relationships. Here is the report:"""
                 }
             ]
    
        assistant.chat(
            messages=inspector_messages,
            model="claude-haiku-4-5",
            max_tokens=1000,
            system=system_prompt
            )
        
        messages.append(inspector_messages)
    
    return messages
    
def observe_behavior_from_profile(profile_json: dict):
    """
        Receives the profiling JSON from the previous steps and spins up agents to
         analyze its behavior, through dynamic filtering.
    """
    messages = []

    system_prompt = load_skill(skill_name="BEHAVIOR")

    for datasource, profile in profile_json.items():
        observer_messages = [
                {
                    "role": "user",
                    "content": (
                    f"""
                        Create a list of dicts for {datasource} containing:
                            - Name of datasource
                            - Column Name
                            - The distinct value to be filter (only one value per row).
                        Follow the expected output pattern of 'filter' argument of read_data_sample tool.
                        Use the profile JSON below to find the appropiate distinct values to filter.
                        {profile} 
                    """
                    ),
                },
                {
                    "role": "assistant",
                    "content": "Here is the list of dicts: ```python"
                }
            ]
    
        assistant.chat(
            messages=observer_messages,
            model="claude-haiku-4-5",
            max_tokens=1000,
            system=system_prompt,
            stop_sequences=["```"]
        )
        
        messages.append(observer_messages)
    
    return messages
   

profile_json = tools.read_profiles(storage_type='local',  folder_path='/Users/julianasampar/Desktop/learning_dev/personal_dev/pyprojects/others/archive/agent_test')
#inspect_structure_from_profile(profile_json)
observe_behavior_from_profile(profile_json)
