"""
inspector.py

Creates an agent to analyze the JSON files generated by the profiler.
"""
from claude.agents.data_discovery_agent__final.tools import tools 
from claude.agents.data_discovery_agent__final.tools.utils import runner

from anthropic import Anthropic
from anthropic.types import Message
from dotenv import load_dotenv

from pathlib import Path

# Loading Anthropic API Key
load_dotenv()

client = Anthropic()

model = "claude-haiku-4-5"
max_tokens=1000

# Defining tools to be called
tools_functions = {
    "read_profiles": tools.read_profiles
}
tools_schemas = [
    tools.read_profiles__schema
]

# Assigning the SKILL as the system prompt
def load_skill() -> str:
    skill_path = Path(__file__).parent / "SKILL.md"
    return skill_path.read_text(encoding="utf-8")

def run_agent(source_type: str, folder_path: str):
    """
    Runs the inspector sub-agent.

    Parameters:
        source_type : the storage type where the profiler JSON files are located. It can be local or AWS.
        folder_path : directory folder of the files.

    Returns the final analysis from the agent.
    """
    system_prompt = load_skill()

    # Assigning the initial user prompt
    messages = [
            {
                "role": "user",
                "content": (
                    f"/read_profiles"
                    f"--source_type {source_type} "
                    f"--folder_path {folder_path}"
                ),
            }
        ]
    
    print(f"[inspector-agent] Reading files located in: {folder_path}")

    response = client.messages.create(
            model=model,
            max_tokens=max_tokens,
            tools=tools_schemas,
            tool_choice={"type": "tool", "name": "read_profiles"}, # Forcing the tool
            messages=messages,
        )
    
    if response.stop_reason != 'tool_use':
        raise ValueError("The Agent could not be executed. Please try again.")
    
    else:
        result = runner.run_tool(response, tools_functions)
        result = result[0]["response"]

        analysis = []

        for datasource, profile in result.items():

            messages = [
                {
                    "role": "user",
                    "content": f"""
                        Analyze the data of {datasource}, with the provided JSON: 
                            {profile}
                        """
                },
                {
                    "role": "assistant",
                    "content": f"""I'll analyze the {datasource} table data and provide you with a comprehensive discovery report covering Primary Keys, Foreign Keys, Orchestration, and Relationships. Here is the report:"""
                }
            ]

            response = client.messages.create(
                model=model,
                max_tokens=max_tokens,
                system=system_prompt,
                tools=tools_schemas,
                messages=messages,
            )

            response = response.content[0].text
            analysis.append({
                            "datasource": datasource,
                            "analysis": response
                            })

            print(f"Analysis of {datasource} completed. Response lenght: {len(response)} caracteres")

        return analysis