{{ config(materialized='table') }}

SELECT 
    tree_id,
    block_id,
    created_at,
    tree_dbh,
    stump_diam,
    curb_loc,
    status,
    health,
    spc_latin,
    spc_common,
    steward,
    guards,
    sidewalk,
    user_type,
    problems,
    root_stone,
    root_grate,
    root_other,
    trunk_wire,
    trnk_light,
    trnk_other,
    brch_light,
    brch_shoe,
    brch_other,
    address,
    postcode,
    zip_city,
    "community board" AS community_board,
    borocode,
    borough,
    cncldist,
    st_assem,
    st_senate,
    nta,
    nta_name,
    boro_ct,
    state,
    latitude,
    longitude,
    x_sp,
    y_sp,
    "council district" AS council_district,
    "census tract" AS census_tract,
    bin,
    bbl
FROM nyc_street_tree_census__2015